spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://68.178.161.177:3306/syndicateadmin_faculty_evaluation_db?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: syndicateadmin_faculty_evaluation_db
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    legacy:
      jdbc-url: jdbc:mysql://119.92.126.122:3306/sisdatabase?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: ict
      password: ${LEGACY_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  cache:
    type: caffeine

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    clean-disabled: true
    validate-on-migrate: true

server:
  port: 9000
  forward-headers-strategy: framework

logging:
  level:
    root: INFO

    # Show generated SQL
    org.hibernate.SQL: DEBUG

    # Show SQL parameters
    org.hibernate.orm.jdbc.bind: TRACE

    # Hibernate warnings/errors
    org.hibernate.orm.jdbc.error: DEBUG

    # Spring Security logs
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}