UPDATE syndicateadmin_faculty_evaluation_db.primary_faculty pf

INNER JOIN primary_class pc
    ON pf.faculty_id = pc.faculty_id

SET pf.college = 'CCS'

WHERE pf.status = 'ACTIVE'

AND (pf.lastname, pf.firstname) IN (
    ('ALEGATA', 'WAYNE CUSTER'),
    ('AZCONA', 'KATRINA'),
    ('BALIDIO', 'JOHN BILLY'),
    ('BARRIENTOS', 'RUBIE LYN'),
    ('BASCOS', 'ANELIA'),
    ('BENEDICTO III', 'ALFONSO JORIE'),
    ('BODOSO', 'ENNA'),
    ('BUSTAMANTE', 'CHRISTINE'),
    ('CASTOR', 'JEAN MICHAEL'),
    ('DABA-AY', 'METHUSELAH'),
    ('DAGUIA', 'AUMAR'),
    ('DECENA', 'AILEEN JOY'),
    ('DE LA CERNA', 'MARIA LUNA'),
    ('DELA RAMA', 'ARLENE'),
    ('DELGADO', 'ALBERT ANTHONY'),
    ('DENISA', 'FEDERICO JR.'),
    ('DORMIDO', 'JOE MARIE'),
    ('ESPINOSA', 'ROGELIO '),
    ('ESGRA', 'NEIL GABRIEL'),
    ('FERNANDEZ', 'MACKY JAY'),
    ('FRIA', 'STELLA MAY'),
    ('FUENTEBELLA', 'DAROEL'),
    ('GARCIA', 'GLEN PETER'),
    ('GAYATIN', 'JOSEPH ABELARDO'),
    ('GONZAGA', 'MARINO JR.'),
    ('GUANZON', 'SUZANNE'),
    ('HORMIGOSO', 'DEXTER'),
    ('JAMANDRON', 'NATHANIEL'),
    ('LAPU-OS', 'EDUARDO JR.'),
    ('LOPEZ', 'JOSHUA'),
    ('LOBRESCO', 'BOBBY'),
    ('MAKILAN', 'NOVEMAY'),
    ('MALAPITAN', 'RUEL'),
    ('MANGANTI', 'MARITES'),
    ('MARGARITO', 'MARVIN'),
    ('MONGE', 'ALBERT JOSEPH GONZALO'),
    ('NALLOS', 'MARK GERALD'),
    ('ORTEGA', 'RETCHELL'),
    ('PABELONA', 'RICHARD JR.'),
    ('PEDREGOSA', 'RONN ELLY'),
    ('PEDROSA', 'EVALYN'),
    ('PLAZA', 'DANILO JR.'),
    ('RASIMO', 'CHRISTINE'),
    ('RAYMUNDO', 'ROLDAN JR.'),
    ('RESUELO', 'BEVERLY'),
    ('REYNOSO', 'MELANIE'),
    ('RIVERA', 'JOSE NALDRIX'),
    ('SABIO', 'CHARMAINE'),
    ('SABIO', 'JOSHUA LANCELOT'),
    ('SALILLAS', 'JOSEPHINE'),
    ('SALMINGO', 'RENE'),
    ('SANTES', 'MA. LORELA'),
    ('SANORIA', 'MARICEL'),
    ('SAYSON', 'KRISTINE'),
    ('SAYSON', 'RONALD JOHN'),
    ('SELISA', 'RENE'),
    ('SERAPIA', 'NEIL BRYAN'),
    ('SOLIDARIOS', 'STEPHEN'),
    ('SUMAGAYSAY', 'MARK FRANCE'),
    ('SY', 'JAYRELLE'),
    ('TALANQUINES', 'MARK JARUS'),
    ('TEN', 'GIOVANI'),
    ('TOGORES', 'MARK ANTHONY'),
    ('TRUJILLO', 'JULIET'),
    ('VINGSON', 'EMILY')
);