UPDATE syndicateadmin_faculty_evaluation_db.primary_faculty pf

INNER JOIN primary_class pc
    ON pf.faculty_id = pc.faculty_id

SET pf.college = 'COF'

WHERE pf.status = 'ACTIVE'

AND (pf.lastname, pf.firstname) IN (
    ('Abeto', 'Arlyn'),
('ADVINCULA', 'EDUARD JOHN'),
('Alabado', 'GERLE MAE'),
('BARREDO', 'Jona'),
('Bedaure', 'ARCHEL'),
('Cajucom', 'Raymar'),
('Cajucson', 'Rolyzer'),
('Cañon', 'Cindy'),
('Cari-an', 'Daisy'),
('Carlton', 'Darryl'),
('Castor', 'Jasmin'),
('Cuales', 'Hancy'),
('Dano', 'Dexter'),
('De la Cruz', 'Alberto'),
('Dejalde', 'Aquiles'),
('Dula', 'PIA'),
('Echanojaurique', 'Virginia'),
('Enema', 'Mira Fe'),
('Enema', 'Ryan'),
('Esparagoza', 'Rolando'),
('Gallano', 'Eden'),
('Ganancial', 'Evangeline'),
('Gañon', 'Vincent'),
('Gapulan', 'Dyan'),
('Gayosa', 'Vivian'),
('Gemoya', 'Enrique Jr.'),
('Geroy', 'Gracel'),
('Gimotea', 'Mac Edmund'),
('Goroy', 'Mary Ann'),
('Guzon', 'Gaily Rey April'),
('Javier', 'Rodolfo Jr.'),
('Juaneza', 'Jennifer'),
('Lagrada', 'Hazel Gay'),
('Linco', 'Joenard'),
('Mabasa', 'Mary Luna'),
('Mahinay', 'Kervin'),
('MALO JR.', 'VICENTE'),
('Mañoso', 'Regina'),
('Manzano', 'Roger Ray'),
('Olmedo', 'Aniceto'),
('Ordonio', 'Andrew'),
('Paniergo', 'Felin'),
('Perante', 'Imee'),
('Ramos', 'Sarah'),
('Ragunel', 'Lowell'),
('Regala', 'Rose'),
('Sisles Jr.', 'Donato'),
('Subornido', 'Rowena'),
('Tabayan', 'Mary Joy'),
('Tanate', 'Romeo'),
('Tejada', 'Rena'),
('Ticar', 'Sheila'),
('Tierra', 'Jose Joey'),
('Tierra', 'Kim Joey Kristoph'),
('Tierra', 'Siari Ann'),
('Tillo', 'Jacquiline'),
('Vergara', 'Joevelle'),
('Villaflor', 'Jose Valery'),
('Zuñiga', 'Ray Anthony')
);