UPDATE syndicateadmin_faculty_evaluation_db.primary_faculty pf

INNER JOIN primary_class pc
    ON pf.faculty_id = pc.faculty_id

SET pf.college = 'CAS'

WHERE pf.status = 'ACTIVE'

AND (pf.lastname, pf.firstname) IN (
('Aboy', 'Ivy'),
('Abrera', 'April'),
('Acanto', 'Ricky'),
('Alayon', 'Nick'),
('Alave', 'Alfredo'),
('Alegada', 'Lucille'),
('Alvarado', 'Arjay'),
('Bangoy', 'Jarebeth'),
('Bascar', 'Jaclyn Joyce'),
('Bascar', 'Jyan Rome'),
('Bearneza', 'Francis Jose'),
('Berina', 'JiJi'),
('Buga-ay', 'Cynthia'),
('Calfoforo', 'Amelia'),
('Cañal', 'Precious Jane'),
('Casili', 'Marivic'),
('CAUDELLOSA JR.', 'Rollie'),
('Cherniguin', 'Ana Magdalena'),
('Chua', 'Marijo'),
('Dagatan', 'Dan'),
('Damaso', 'Ma. Elizabeth'),
('Deocadez', 'Riza'),
('Desabella', 'Romeo Jr.'),
('Dioneo', 'Ma. Salud'),
('Elano', 'Annabelle'),
('Ella', 'John Mil'),
('Estares', 'Soledad'),
('Estrellas', 'Jay'),
('Fernandez', 'Maria Thirza'),
('Fernando', 'Analie'),
('Franco', 'Lendi Lee'),
('Garcia', 'Joyzel Rey'),
('Granfiel', 'Lovelyn'),
('Guanzon', 'GECIELA'),
('Gonzales', 'Carina Christine'),
('Herrera', 'SAMUEL JR.'),
('Impil', 'Leonisa'),
('Javier', 'Rufus'),
('Lampinez', 'Jose Lizael'),
('Langcoy', 'Mary Grace'),
('Linaja', 'Rhea'),
('Lobaton', 'Vince Paul'),
('Mamac', 'Noel'),
('Manalo', 'Ma. Riza'),
('Mario', 'Julie Ann'),
('Mateo', 'Brendly Ann'),
('Maquiling', 'Everlou'),
('Mendoza', 'Rey'),
('Morales', 'Ma. Elena'),
('Nemenzo', 'Ruth'),
('Nuarbe', 'Venus'),
('Orleans', 'CHIRYL'),
('Palermo', 'Juben'),
('Pardillo', 'Robert'),
('Parpa', 'Zion Rose'),
('Peracullo', 'May'),
('Picar', 'Joy'),
('Pineda', 'Jesusa'),
('Rivera', 'Roxanne'),
('Salde', 'Yvonne'),
('Samonte', 'Rhoderick'),
('Sian', 'JULIAN JR'),
('Sigaya', 'Ma. Graziella'),
('Solomon', 'Richard'),
('Soldevilla', 'Nelson'),
('Somcio', 'Paz Marie Phillane'),
('Tranquilo', 'Aileen'),
('Tumabing', 'Jansen'),
('Tumlos', 'Johnrie'),
('Tuscano', 'MA. ROWENA'),
('Velasco', 'Yvonne'),
('Venegas', 'Rosemarie'),
('Violanda', 'Maria Victoria'),
('Bibangco', 'El Jireh'),
('Mondero', 'NORBERTO JR.')
);